### ISSUE TITLE
Combobox low contrast for selected item with component renderer

### ISSUE THREAD

**Issue by mrgreywater** [parttio/breeze-theme#4]
When using a Combobox with a custom component renderer, the text color is similar to the highlighted field background.

**Comment by juuso-vaadin** [comment]
Using component renderer in Combo Box shouldn't interfere with the theme. I wasn't able to replicate the issue, could you elaborate a bit on what you're doing to get this issue?

**Comment by mrgreywater** [comment]
Here is an example that looks fine with default Lumo, but with breeze it's difficult to see what's written with a selected item.

```java
public static class Item {
    public int id;

    public Item(int i) {
        this.id = i;
    }
}
```

```java
var items = new ArrayList<Item>();
for (int i = 0; i < 100; i++) {
    items.add(new Item(i));
}
var combobox = new ComboBox<Item>();
combobox.setItems(items);
combobox.setItemLabelGenerator(c -> "Item No." + c.id);
combobox.setRenderer(new ComponentRenderer<>(c -> {
    var button = new Button("Item No.", VaadinIcon.UPLOAD.create());
    button.addThemeVariants(ButtonVariant.LUMO_TERTIARY_INLINE);
    button.addThemeVariants(ButtonVariant.LUMO_SMALL);
    return button;
}));
add(combobox);
```

Sure, I could simply not use a button as a component, but I think it's an issue nevertheless, as it works fine with any other theme.

**Comment by juuso-vaadin** [comment]
Ok, the issue originates from the selected item having a background-color which isn't the case with Lumo theme. I won't add the styling to project as placing other components in the overlay with renderer would have similar issue and we cannot cover for all possible cases. I can recommend not using a button in the dropdown, but rather a simple div.

Here are the styles you'll need to target the button if you'd still like to stick to your solution.
```
vaadin-combo-box-item[selected] vaadin-button {
    color: var(--lumo-primary-contrast-color);
}
```

**Comment by juuso-vaadin** [comment]
Here's renderer snippet for using a HorizontalLayout instead of Button.
```
combobox.setItemLabelGenerator(c -> "Item No." + c.id);
combobox.setRenderer(new ComponentRenderer<>(c -> {
       var item = new HorizontalLayout();
       item.add(VaadinIcon.UPLOAD.create(), new Text("Item No." + c.id));
       item.setSpacing(false);
       item.getThemeList().add("spacing-s");
       return item;
}));
```
